source 'https://github.com/CocoaPods/Specs.git'

target 'GDGeoData', :exclusive => true do
  pod "GDGeoData", :path => "../"

  pod 'Specta', '~> 0.2.1', :inhibit_warnings => true
  pod 'Expecta'           , :inhibit_warnings => true
  pod 'OCMockito', '~> 1.0'

end

